image: gitpod/workspace-full

additionalRepositories:
  # Java-app with maven
  - url: https://gitlab.com/twn-devops-bootcamp/latest/04-build-tools/java-maven-app
  # Java-app with gradle
  - url: https://gitlab.com/twn-devops-bootcamp/latest/04-build-tools/java-app
  # React-nodejs-app
  - url: https://github.com/techworld-with-nana/react-nodejs-example

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Upgrade Java, Gradle
    init: |
      sdk install Java
      sdk install gradle

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3080 for the react-nodejs-example
    port: 3080
    onOpen: open-preview
  - name: Nexus
    description: Port 8081 for Nexus repository manager
    port: 8081
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
