image: gitpod/workspace-full

additionalRepositories:
  # Java-app with maven
  - url: https://gitlab.com/twn-devops-bootcamp/latest/04-build-tools/java-maven-app
  # Java-app with gradle
  - url: https://gitlab.com/twn-devops-bootcamp/latest/04-build-tools/java-app
  # React-nodejs-app
  - url: https://github.com/techworld-with-nana/react-nodejs-example

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
#tasks:
# - name: Script Task
#    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
#    command: echo 'start script'
#     - name: Static Server
#       command: python3 -m http.server 8080
#     - name: DB Server
#       command: sh ./scripts/start-db.sh
#       openMode: split-right
# - name: Dependencies & Database
#   init: |
#       npm install
#       npm run configure-database
#   command: npm run dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
