BOX = "fedora/39-cloud-base"
BOX_VERSION = "39.20231031.1"
HOSTNAME = "twitch"
CPUS = 2
# original: 4
MEMORY = "2048"
# original: 8192
USER_NAME = "fedora"
PASSWORD = "fedora"
KEYMAP = "us"

Vagrant.configure("2") do |config|
    config.vm.box = BOX
    config.vm.box_version = BOX_VERSION
  
    config.vm.hostname = HOSTNAME

    config.vm.provider "virtualbox" do |virtualbox|
        virtualbox.gui = true        
        virtualbox.cpus = CPUS
        virtualbox.memory = MEMORY
        virtualbox.name = HOSTNAME

        virtualbox.customize ['modifyvm', :id, '--accelerate3d', 'on']
        virtualbox.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
        virtualbox.customize ['modifyvm', :id, '--vram', '64']
        # original: 128
    end

    config.vm.provision "main", type: "shell", args: [USER_NAME, PASSWORD, KEYMAP], run: "never", path: "provisioner/main.sh"

    config.vm.provision "ansible", type: "shell", run: "never", path: "provisioner/ansible.sh"

    config.vm.provision "final", type: "shell", args: [USER_NAME], run: "never", path: "provisioner/final.sh"
end
  