def gv

pipeline {
  agent any
    tools {
      maven 'Maven'
    }
  stages {
    stage("init") {
      steps {
        script {
          gv = load "script.groovy"
        }
      }
    }
    // Run tests on all branches
    stage("test") {
      steps {
        script {
          gv.testApp()

        }
      }

    }
    // Only build, deploy when in main branch
    stage("build") {
      when {
        expression {
          BRANCH_NAME == "main"
        }
      }
      steps {
        script {
          gv.build()

        }
      }
    }

    stage("build image") {
      when {
        expression {
          BRANCH_NAME == "main"
        }
      }
      steps {
        script {
          gv.buildImage()
        }
      }
    }

    stage("deploy") {
      when {
        expression {
          BRANCH_NAME == "main"
        }
      }
      steps {
        script {
          gv.deployApp()
        }
      }
    }
  }
}

