# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ############################################################
  # VirtualBox Hypervisor Configuration
  ############################################################

  # For workloads needing 1 CPU, 2 GB RAM
  config.vm.define "cli-small", primary: true do |clismall|
    clismall.vm.box = "ubuntu/jammy64"

    clismall.vm.provider :virtualbox do |vb|
      vb.name = "clismall"
      # Allocate memory from 1 GB default to 2 GB for kubernetes workloads
      vb.memory = "2048"
    end
  end

  # For workloads needing 1 CPU, 2 GB RAM
  config.vm.define "cli-small-pb", primary: true do |clismallpb|
    clismallpb.vm.box = "justunsix/bento-ubuntu-24.04-nix"

    clismallpb.vm.provider :virtualbox do |vb|
      vb.name = "clismall"
      # Allocate memory from 1 GB default to 2 GB for development workload
      vb.memory = "2048"
    end

    # Increase timeout as first boot can take time
    clismallpb.vm.boot_timeout = 700
  end

  # For workloads needing 1 CPU, 1 GB RAM (default Ubuntu image settings)
  config.vm.define "cli-micro", primary: true do |climicro|
    climicro.vm.box = "ubuntu/jammy64"

    climicro.vm.provider :virtualbox do |vb|
      vb.name = "climicro"
    end
  end

  # Source of desktop config: 
  # https://github.com/Simon-Str/Aufbau-einer-Smarthome-Security-Umgebung/blob/main/Vagrantfile
  config.vm.define "desktop-medium" do |desktopmedium|
    desktopmedium.vm.box = "ubuntu/jammy64"

    desktopmedium.vm.provider :virtualbox do |vb|
      # Set VM name
      vb.name = "Ubuntu Jammy Desktop"
      # Allocate memory
      vb.memory = "4096"
      # Assign CPUs
      vb.cpus = "2"
      # Enable GUI
      vb.gui = true
      # Specify graphics controller
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
      # Set video RAM size
      vb.customize ['modifyvm', :id, '--vram', '128']
      # Enable bidirectional clipboard sharing
      vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
      # Enable bidirectional drag and drop
      vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      # Configure audio settings: Use DirectSound driver and AC'97 audio controller
      #vb.customize ["modifyvm", :id, '--audio', 'dsound', '--audiocontroller', 'ac97']
      # Accelerate graphics
      vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
      # vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
      # Add DVD Drive for VirtualBox Guest additions later
      vb.customize ['storageattach', :id, 
                '--storagectl', 'IDE', 
                '--port', '0', '--device', '1', 
                '--type', 'dvddrive', 
                '--medium', 'emptydrive']

      # Permit password authentication because broken vagrant publickey authentication
      desktopmedium.vm.provision "shell", inline: <<-SHELL, run: "always"
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        sudo systemctl restart sshd
      SHELL

    end

  end

  # Access to web app 3000 and admin ui 8081
  config.vm.network "forwarded_port", guest: 3000, host: 3000,
    auto_correct: true
  config.vm.network "forwarded_port", guest: 8081, host: 8081,
    auto_correct: true

  ############################################################
  # Mount repositories from the host
  ############################################################

  # If exists, mount ~/Code from Host to vagrant's $HOME/Code/
  if File.directory?(File.expand_path("#{ENV['HOME']}/Code"))
    config.vm.synced_folder "#{ENV['HOME']}/Code", "/home/vagrant/Code/"
  end

  # If exists, copy ~/.ssh from Host to vagrant
  if File.directory?(File.expand_path("#{ENV['HOME']}/.ssh"))
    config.vm.provision "file", run: "always", source: "#{ENV['HOME']}/.ssh", destination: "~"
  end

  ############################################################
  # Provisioners
  ############################################################

  config.vm.provision "main-setup", type: "shell", run: "never", path: "provisioner/main-setup.sh"

  config.vm.provision "activate-ansible", type: "shell", run: "never", path: "provisioner/activate-ansible.sh"

  config.vm.provision "activate-devops", type: "shell", run: "never", path: "provisioner/activate-devops.sh"

  config.vm.provision "activate-editor", type: "shell", run: "never", path: "provisioner/activate-editor.sh"

  config.vm.provision "gnome", type: "shell", run: "never", path: "provisioner/desktop-gnome.sh"

  config.vm.provision "nix", type: "shell", run: "never", path: "provisioner/nix.sh"

  config.vm.provision "azure-cli", type: "shell", run: "never", path: "provisioner/azure-cli.sh"

  config.vm.provision "nix-home-manager", type: "shell", run: "never", privileged: false, path: "provisioner/nix-home-manager.sh"

  config.vm.provision "lazyvim", type: "shell", run: "never", privileged: false, path: "provisioner/lazyvim.sh"

  config.vm.provision "docker"

  config.vm.provision "k3s", type: "shell", run: "never", privileged: false, path: "provisioner/k3s.sh"

end  
