apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      # See image on repository for options
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          # Environment variables for DB connectivity
          # Reuse existing DB Secrets
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            # Use ConfigMap to allow reuse of database connection
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  # type LoadBalancer means it is an External Service
  # Will assign external IP address
  # Internal service will have type ClusterIP (default value)
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      # targetPort will be mapped to nodePort (external port)
      targetPort: 8081
      # nodePort is a range from 30000-32767 and used for external access
      nodePort: 30000

