# Install Nix package manager
# From https://github.com/danielrolls/nix-install
# hostname for Vagrant is usually default
- hosts: all
  roles:
    - role: danielrolls.nix
      nix_commands:
      - "nix-shell -p nix-info --command nix-info" 

  tasks:
    - name: Install Nix packages
      ansible.builtin.command: "/nix/var/nix/profiles/default/bin/nix-env -iA {{ item }}"
      loop:
        - nixpkgs.kubectl
        - nixpkgs.zoxide
        - nixpkgs.nushell
        - nixpkgs.starship
        - nixpkgs.carapace
        - nixpkgs.broot
        - nixpkgs.atuin
    # Run broot --install in shell, run as user
    - name: Run broot --install
      ansible.builtin.command: "/home/vagrant/.nix-profile/bin/broot --install"
      become: true
      become_user: vagrant