# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ############################################################
  # VirtualBox Hypervisor Configuration
  ############################################################

  config.vm.define "k8stest", primary: true do |k8stest|
    k8stest.vm.box = "ubuntu/jammy64"

    k8stest.vm.provider :virtualbox do |vb|
      vb.name = "k8stest"
      # Allocate memory from 1 GB default to 2 GB
      vb.memory = "2048"
    end
  end

  ############################################################
  # Provisioners
  ############################################################

  config.vm.provision "shell", inline: <<-SHELL
    echo -e "-- Updating system"
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt install curl -y
  SHELL

  # Run script to install k8s components and tools
  config.vm.provision "main-setup", type: "shell", privileged: false, path: "setup-vm.sh"
  config.vm.provision "tools-setup", type: "shell", privileged: false, path: "setup-tools.sh"
  
  config.vm.provision "docker"

end
