apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        # See image on repository for options
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          # Database credentials as Secrets
          # Do not store credentials here
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              # Reference Secret and keys inside it
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      # targetPort must match containerPort of pods
      targetPort: 27017
