apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-two
  labels:
    app: my-app-two
spec:
  replicas:
  selector:
    matchLabels:
      app: my-app-two
  template:
    metadata:
      labels:
        app: my-app-two
    spec:
      # Image repository credentials
      # Secret must be in same namespace for deployment
      imagePullSecrets:
        - name: my-registry-key-two
      containers:
        - name: my-app-two
          # Example image name with tag: 12414.ecr.amazonaws.com/my-app:1.2
          # containing repository
          image: IMAGE_NAME_HERE
          # Force pull on deployment
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
